### ISSUE TITLE
Cnnot send mouse data

### ISSUE THREAD

**Issue by GluTbl** [AnesBenmerzoug/Bluetooth_HID#1]
when i run "sudo python /home/pi/Bluetooth_HID/user_interface.py"
it says

pi@raspberrypi:~ $ sudo python /home/pi/Bluetooth_HID/user_interface.py
/usr/lib/python2.7/dist-packages/gtk-2.0/gtk/__init__.py:57: GtkWarning: could n                                                                                        ot open display
  warnings.warn(str(e), _gtk.Warning)
Setting up service
Setting up DBus Client
Setting up Bluetooth device
Configuring for name Bluetooth_Keyboard/Mouse
Setting up DBus Client
Waiting for keyboard
Traceback (most recent call last):
Waiting for mouse
  File "/home/pi/Bluetooth_HID/user_interface.py", line 411, in <module>
    root = Tk()
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1823, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, want                                                                                        objects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
Found a keyboard with the keyword 'mouse'
device name is USB OPTICAL MOUSE
Mouse Found
Starting mouse event loop
Keyboard not found after 100 tries
Configuring Bluez Profile
Reading service record
Profile registered
Waiting for connections
ERROR:dbus.proxies:Introspect error on :1.78:/org/upwork/HidBluetoothService: db                                                                                        us.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Message recipie                                                                                        nt disconnected from message bus without replying
Couldn't send mouse input

**Comment by speicherspule** [comment]
same here
